language: c

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lv2 fftw; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq lv2-dev libfftw3-dev

script:
  - make
