name: noise-repellent
version: git
grade: stable
architectures: [amd64, i386]
summary: Noise Repellent
description: |
  An lv2 plugin for broadband noise reduction.

confinement: devmode

parts:
  noise-repellent:
    plugin: make
    source: https://github.com/lucianodato/noise-repellent.git
    source-type: git
    build-packages:
      - g++
      - make
      - pkg-config
      - lv2-dev
      - libfftw3-dev
    artifacts: [build/nrepel.so, build/manifest.ttl, build/nrepel.ttl]
    install: |
      rm -rf /$HOME/.lv2/nrepel.lv2/
      mkdir -p /$HOME/.lv2/nrepel.lv2/
      cp -af $SNAPCRAFT_PART_INSTALL/build/. /$HOME/.lv2/nrepel.lv2/